# URL base da API
base.url=https://jsonplaceholder.typicode.com

# Ambiente (dev, qa, prod)
env=qa

# Timeout
timeout=5000

# Autenticação
api.token=123456789

# Headers padrão
content.type=application/json

# Logs
log.level=ALL